### ISSUE TITLE
fps parameter is static

### ISSUE THREAD

**Issue by Sundowndev** [transitive-bullshit/ffmpeg-generate-video-preview#3]
```
$ generate-video-preview bbb_sunflower_1080p_30fps_normal.mp4 output.gif --width 320 --num-frames 60 --fps 30
{ cmd:
   'ffmpeg -i bbb_sunflower_1080p_30fps_normal.mp4 -y -vsync vfr -q:v 2 -vf select=not(mod(n\\,634)),scale=320:-1 /tmp/5f868a01dc1e7dd62f5e66902812d43e/frame-%d.png' }
gifski -o output.gif --fps 10 --quality 80 --quiet /tmp/5f868a01dc1e7dd62f5e66902812d43e/frame-*.png
{
  "output": "output.gif",
  "numFrames": 30,
  "width": 320,
  "height": 180
}
```

Whatever I set as fps param, it still use 10 as value. 60 frames as 30 fps should give me a gif of 2 sec right ?

EDIT: ok just figured out the ffmpeg command does not take 30 side by side frames, the gif is 2sec long but with random frames.

EDIT2: working with `-f`

**Comment by transitive-bullshit** [comment]
I just released a bugfix `1.0.2` because CLI args weren't always being parsed properly.

Does this fix your issue?

**Comment by transitive-bullshit** [comment]
To confirm, the `--gif-fps` parameter isn't working, but `-f` is working for you?

**Comment by Sundowndev** [comment]
Ok I just figured out.. There's a mistake in your example : `generate-video-preview big-buck-bunny.avi output.gif --width 320 --num-frames 30 --fps 4`

It's `--gif-fps` not `--fps`, I tested without reading the help command :)

**Comment by transitive-bullshit** [comment]
Just updated the readme :)
